# gum CLI theme - Phosphor Green
# https://github.com/charmbracelet/gum
#
# Old school CRT terminal aesthetic
# Bright greens and ambers on solarized dark background
#
#   Phosphor Green: 46 (bright), 71 (medium), 65 (dim), 22 (dark)
#   Amber:          214 (bright), 172 (medium), 130 (dark)

# input
export GUM_INPUT_CURSOR_FOREGROUND="46"
export GUM_INPUT_PROMPT_FOREGROUND="71"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="65"
export GUM_INPUT_HEADER_FOREGROUND="214"

# choose
export GUM_CHOOSE_CURSOR_FOREGROUND="46"
export GUM_CHOOSE_HEADER_FOREGROUND="214"
export GUM_CHOOSE_ITEM_FOREGROUND="65"
export GUM_CHOOSE_SELECTED_FOREGROUND="16"
export GUM_CHOOSE_SELECTED_BACKGROUND="46"

# filter
export GUM_FILTER_INDICATOR_FOREGROUND="46"
export GUM_FILTER_PROMPT_FOREGROUND="71"
export GUM_FILTER_PLACEHOLDER_FOREGROUND="65"
export GUM_FILTER_HEADER_FOREGROUND="214"
export GUM_FILTER_TEXT_FOREGROUND="65"
export GUM_FILTER_CURSOR_TEXT_FOREGROUND="214"
export GUM_FILTER_MATCH_FOREGROUND="46"
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="46"
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="65"

# confirm
export GUM_CONFIRM_PROMPT_FOREGROUND="214"
export GUM_CONFIRM_SELECTED_FOREGROUND="16"
export GUM_CONFIRM_SELECTED_BACKGROUND="46"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="65"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="22"

# spin
export GUM_SPIN_SPINNER_FOREGROUND="46"
export GUM_SPIN_TITLE_FOREGROUND="71"

# write
export GUM_WRITE_CURSOR_FOREGROUND="46"
export GUM_WRITE_PROMPT_FOREGROUND="71"
export GUM_WRITE_PLACEHOLDER_FOREGROUND="65"
export GUM_WRITE_HEADER_FOREGROUND="214"
export GUM_WRITE_LINE_NUMBER_FOREGROUND="65"
export GUM_WRITE_CURSOR_LINE_NUMBER_FOREGROUND="71"

# pager
export GUM_PAGER_BORDER_FOREGROUND="71"
export GUM_PAGER_LINE_NUMBER_FOREGROUND="65"
export GUM_PAGER_MATCH_FOREGROUND="214"
export GUM_PAGER_MATCH_BOLD="true"
export GUM_PAGER_MATCH_HIGH_FOREGROUND="16"
export GUM_PAGER_MATCH_HIGH_BACKGROUND="214"
